### ISSUE TITLE
AttributeError: 'BatchIterator' object has no attribute 'split'

### ISSUE THREAD

**Issue by harshuljain13** [litan/tefla#14]
I had a fresh install on my system, and suddenly I have been facing the issue with this error.

This error comes up when I run train_withf command.

```
python -m tefla.train_withf --model examples/imagenet_tl_feature_extract/bottleneck_model.py --training_cnf examples/imagenet_tl_feature_extract/train_cnf.py --data_dir ../datasets/csx/data-view/ --start_epoch 1 --resume_lr 0.01 --visuals True
```

Error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/h_hack/work/pywork/ML/tefla/tefla/train_withf.py", line 51, in <module>
    main()
  File "/home/h_hack/work/pywork/ML/tefla/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/h_hack/work/pywork/ML/tefla/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/h_hack/work/pywork/ML/tefla/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/h_hack/work/pywork/ML/tefla/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/h_hack/work/pywork/ML/tefla/tefla/train_withf.py", line 47, in main
    summary_every=cnf.get('summary_every', 10), clean=clean, visuals=visuals)
  File "tefla/core/training.py", line 44, in fit
    self._setup_optimizer()
  File "tefla/core/training.py", line 291, in _setup_optimizer
    util.trainable_variables(self.trainable_scopes))
  File "tefla/utils/util.py", line 176, in trainable_variables
    scopes = [scope.strip() for scope in trainable_scopes.split(',')]
AttributeError: 'BatchIterator' object has no attribute 'split'
```
Details:
I am using non Anaconda environment.
```
appdirs (1.4.3)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
bleach (2.0.0)
certifi (2017.4.17)
click (6.6)
configparser (3.5.0)
cycler (0.10.0)
dask (0.14.1)
decorator (4.0.11)
entrypoints (0.2.2)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
ghalton (0.6)
html5lib (0.999999999)
ipykernel (4.6.1)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
MarkupSafe (1.0)
matplotlib (1.5.3)
mistune (0.7.4)
mock (2.0.0)
nbconvert (5.1.1)
nbformat (4.3.0)
networkx (1.11)
notebook (5.0.0)
numpy (1.12.1)
packaging (16.8)
pandas (0.18.1)
pandocfilters (1.4.1)
pathlib2 (2.2.1)
pbr (3.0.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (2.3.0)
pip (9.0.1)
prompt-toolkit (1.0.14)
protobuf (3.2.0)
psutil (5.0.0)
ptyprocess (0.5.1)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2017.2)
pyzmq (16.0.2)
qtconsole (4.3.0)
scandir (1.5)
scikit-image (0.12.3)
scikit-learn (0.18.1)
scipy (0.18.0)
setuptools (35.0.1)
SharedArray (1.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
tefla (0.1, /home/h_hack/work/pywork/ML/tefla)
tensorflow (1.1.0)
terminado (0.6)
testpath (0.3)
toolz (0.8.2)
tornado (4.5.1)
traitlets (4.3.2)
virtualenv (15.1.0)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.12.1)
wheel (0.29.0)
widgetsnbextension (2.0.0)
```

**Comment by litan** [comment]
In train_withf, change the last 3 lines of main() with the following (note the extra None in the constructor and fit() function calls): 

```
    trainer = SupervisedTrainer(model, cnf, None, training_iter, validation_iter, classification=cnf['classification'])
    trainer.fit(data_set, weights_from, None, start_epoch, resume_lr, verbose=1,
                summary_every=cnf.get('summary_every', 10), clean=clean, visuals=visuals)

```
Let me know if that fixes the problem.

**Comment by harshuljain13** [comment]
@litan  this is great. this is the great fix. It is working now. Shouldn't we commit this change as well?

**Comment by litan** [comment]
Yes. Done.
